name: flame_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.33.0
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  shared_preferences: ^2.5.3
  flutter_switch: ^0.3.2
  flame_audio: ^2.11.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/levels/levels.json
    - assets/eggs/eggs.json
    - assets/images/avatars/
    - assets/images/eggs/
    - assets/audio/

  fonts:
    - family: RubikMonoOne
      fonts:
        - asset: assets/fonts/RubikMonoOne-Regular.ttf
          style: normal
